export const configEN: {
  name: string;
  list: string[];
}[] = [
  {
    name: "Dating",
    list: [
      "Meow three times",
      "Take a funny selfie together",
      "Whisper to each other",
      "Press the other person's calf for 1 minute",
      "Maintain eye contact for 5 seconds",
      "Feed each other water",
      "Hold hands for 30 seconds",
      "Hug for 30 seconds",
      "Maintain eye contact for 5 seconds",
      "Attempt to kiss",
      "Share your first impression of each other",
      "Hold hands for one minute",
      "Let the other person close their eyes while you apply lipstick",
      "Give each other a massage",
      "Act out Zhu Bajie carrying his wife",
      "Touch the other person's ear for 2 seconds",
      "Pat the other person's head for 10 seconds",
      "Sing a song to each other",
      "Have a drink together",
      "Attempt to kiss again",
      "Create a confession video for each other as a memory",
      "Comb the other person's hair",
      "Have the other person stand while you kneel and feed them",
      "Give the other person a 1-minute massage on their back",
      "Meow three times",
      "Kiss the back of the other person's hand for 30 seconds",
      "Hug for one minute",
      "Maintain eye contact for 5 seconds",
      "Take another funny selfie",
      "Kiss the other person's hand",
      "[Penalty] Be tickled for 30 seconds",
      "Hug from behind for 1 minute",
      "Kiss the other person's forehead",
    ],
  },
  {
    name: "Passionate love",
    list: [
      "Gently blow air near the other person's ear 10 times",
      "Kiss in front of a mirror",
      "Sequentially kiss the other person's face, neck, and collarbone",
      "Lie down and give the other person a 1-minute massage",
      "Press the other person under you and do ten push-ups",
      "Both crawl under the covers and kiss",
      "Maintain eye contact for 20 seconds",
      "Take a shower together on the same day",
      "Raise your buttocks and let the other person spank you 10 times",
      "Gently touch the sensitive area of the other person for 30 seconds",
      "Hug each other for 1 minute and caress each other's buttocks",
      "The guy princess-carries the girl and holds for 15 seconds",
      "Close your eyes and let the other person do whatever they want for 1 minute",
      "Kiss the other person's cheek",
      "French kiss for 30 seconds",
      "Gently rub the other person's buttocks",
      "Take off the specified clothing of the other person",
      "Gently touch the other person's chest for 30 seconds",
      "French kiss with a method for 20 seconds",
      "Take off one piece of clothing",
      "Kneel down and kiss the other person's hand",
      "Gently touch the other person's thighs for 30 seconds",
      "Kiss the other person's chest for 30 seconds",
      "Turn away and wiggle your butt towards the other person",
      "Buy a sexy item",
      "Do nothing",
      "Take off one piece of clothing",
      "Gently lick the other person's earlobe for 10 seconds",
      "Use an ice cube to gently slide over the other person's body until it melts",
      "Give the other person a gentle foot massage for 2 minutes",
      "Perform a sexy dance for 1 minute",
      "Blindfold the other person with a scarf or blindfold and play a sensory exploration game",
      "Watch an erotic movie together or read an erotic novel, then discuss your feelings",
      "Create a sexual guide for both of you, including preferences, desires, and limits",
      "Find a quiet outdoor spot, kiss the other person's entire body, and enjoy the beauty of nature",
      "Use food for kissing and licking, such as chocolate sauce or fresh fruit",
      "Experiment with new sexual positions or techniques together for added excitement",
      "Gently stimulate the other person's ear with your tongue",
      "Gently bite the other person's earlobe",
      "Give the other person a relaxing shoulder massage",
      "Gently caress the other person's lower body for 30 seconds, providing pleasure",
      "Close your eyes and let the other person do anything to you for one minute",
      "Gently knead the other person's buttocks",
      "Remove any piece of clothing as specified by the other person",
      "Gently caress the other person's chest for 30 seconds",
      "Try a new intimate position together",
      "Use your hands to gently touch sensitive areas on each other",
      "Slide an ice cube over the other person's body for 30 seconds",
      "Write a sweet message on the other person's body with lipstick",
      "Put on sexy lingerie and give the other person a private performance",
      "Sing a song or recite a poem for the other person",
      "Imitate the other person's voice and mannerisms, playing a role-playing game",
      "Expose yourself for a moment on the balcony or in the garden, enjoying the natural sensations",
      "Wear a blindfold until the end of the game",
    ],
  },
  {
    name: "Cohabitation",
    list: [
      "Take off the other person's underwear",
      "Lick the other person's ears for 10 seconds",
      "Give the other person a leg massage",
      "[Bonus] Lie down, and let the other person massage you for one minute",
      "Deeply kiss the other person for 30 seconds",
      "Tickle the other person until they beg for mercy, at least 10 seconds",
      "Take off one piece of clothing from the other person",
      "Take off all of the other person's clothes",
      "Tease sensitive areas of the other person for 15 seconds",
      "Let the other person grab your chest inside your underwear for 10 seconds",
      "The woman is princess-carried by the man and they walk around the room once",
      "Pour alcohol or yogurt on yourself, and let the other person lick it clean",
      "Take a selfie video of you kissing",
      "Drink a toast and take a photo",
      "Strip completely",
      "Suck the other person's fingers with your mouth for 10 seconds",
      "Let the other person lick various parts of your upper body for more than 30 seconds",
      "Lay down, and let the other person lick your back for 20 seconds",
      "Suck the other person's chest for 20 seconds",
      "Wet kiss with the other person for 10 seconds",
      "Kiss the inside of the other person's thighs for 10 seconds",
      "Strip completely",
      "Tie the other person's hands until the punishment is over",
      "Touch the other person's chest or spank their buttocks once",
      "Let the other person's hand touch inside your pants and freely touch for 10 seconds",
      "[Bonus] Let the other person perform oral sex on you for 30 seconds",
      "Massage the other person's breasts for a moment",
      "Lick the other person's neck to chest for 30 seconds",
      "Lick or lightly bite the other person's earlobe five times",
      "Kneel down and lick the other person for 30 seconds",
      "[Bonus] Lie down and enjoy being licked all over your body by the other person for 1 minute",
      "Try to make the other person aroused or wet in any way",
    ],
  },
  {
    name: "Advancing",
    list: [
      "Help the opponent hold the testicles or clitoris for 10 seconds while swirling the tongue",
      "[Penalty] Raise your buttocks and let the other person spank you three times",
      "[Bonus] The other person gives you oral pleasure in a designated area for one minute",
      "Apply oil, chest to chest, and help the opponent push the chest for 30 seconds",
      "Lick the opponent's silk feet or fingers for 10 seconds",
      "Strip naked [or wear sexy lingerie]",
      "Wet kiss with the opponent for 10 seconds",
      "Suck the opponent's fingers for 10 seconds",
      "The woman wears sexy lingerie, and the man licks the opponent's back for 1 minute",
      "Let the opponent bite and rub the nipple with their teeth for 10 seconds",
      "[Bonus] The opponent kisses you with water on your body for 30 seconds",
      "Hold the opponent's testicles or clitoris in your mouth for 10 seconds",
      "Reach from behind and massage the chest for 30 seconds",
      "Rear-entry thrust 20 times without ejaculating",
      "Have mutual breast sex for 30 seconds",
      "Let the opponent bite and rub the nipple with their teeth for 10 seconds",
      "Pour yogurt on the opponent's nipple and lick it clean",
      "Massage the opponent's chest 3 times or lightly bite the opponent's earlobe 5 times",
      "Do everything possible to make the opponent aroused or wet",
      "Rear-entry penetration 20 times and record a video for memories",
      "Record a 15-second video of giving oral pleasure to the opponent",
      "The man stands, lifts the woman, and inserts 20 times without ejaculating",
      "Record a video of fondling the breasts in front of a mirror for 10 seconds",
      "Rub the face of the opponent with your chest or genitals for 10 seconds",
      "Lick the opponent's neck to chest for 30 seconds",
      "Practice Kama Sutra's 'Lotus' position for 30 seconds without ejaculating",
      "[Bonus] The opponent licks various parts of your body for 1 minute",
      "[Bonus] The opponent helps you by licking all parts of your body for 2 minutes",
      "Hold the opponent's testicles or clitoris in your mouth for 30 seconds",
      "Let the opponent use their genitals to slap your face 3 times or rub them on your face for 10 seconds",
      "Use your hand to stimulate yourself for 1 minute or [do something else] 30 times",
      "Hold hot water in your mouth and give oral pleasure to the opponent for 30 seconds",
      "Record a video of lovemaking with the opponent",
      "Hold ice water or ice in your mouth and give oral pleasure to the opponent for 30 seconds",
      "The opponent stands while you kneel and help them [him/her] orally for 1 minute",
      "Rear-entry thrust 20 times without ejaculating",
    ],
  },
  {
    name: "Intimacy",
    list: [
      "French kiss with the partner for 10 seconds",
      "Get the partner aroused or wet",
      "Lick the opponent's neck to chest for 30 seconds",
      "[Penalty] The opponent sits on you with their back facing until the end of the game",
      "Give the partner oral sex for 15 seconds",
      "Strip naked",
      "Suck and bite the partner's nipples for 20 seconds",
      "[Bonus] The partner feeds you with their mouth",
      "Take a photo of giving oral sex to the partner",
      "Make love while talking on the phone with parents",
      "Hold the opponent's testicles or clitoris in your mouth for 10 seconds",
      "Rear-entry thrust 20 times without ejaculating",
      "Massage the partner's chest or tweak it",
      "Have mutual breast sex for half a minute",
      "The partner stands while you kneel and help them [him/her] orally for 10 seconds",
      "Pour yogurt on the partner's nipple, lick it clean, and eat it",
      "Let the partner pull out one hair",
      "Suck and nibble on the partner's fingers for 10 seconds like oral sex",
      "Open the door and have oral sex at the doorway for 10 seconds",
      "Record a video of fondling the breasts in front of a mirror for 10 seconds",
      "Rub the partner's face with your breast or genitals for 10 seconds",
      "Hold the partner's testicles or clitoris in your mouth for 10 seconds",
      "Lick the partner's neck to chest for 30 seconds",
      "Let the partner step on your chest or testicles for 10 seconds",
      "French kiss with the partner for half a minute",
      "The partner stands while you kneel and help them [him/her] orally for 10 seconds",
      "Hold the partner's testicles or clitoris in your mouth for half a minute",
      "Suck and bite the partner's nipples for 30 seconds",
      "Rear-entry for one minute in front of the mirror, no ejaculating allowed",
      "The partner stands while you kneel and help them [him/her] orally for one minute",
      "Lick from the forehead down to the toes",
      "The opponent pours water from the base of your thighs, and you drink it all",
      "Specify any part of your body for the partner to lick for 20 seconds",
      "Wear a blindfold and enjoy the partner licking any part for one minute",
    ],
  },
  {
    name: "Outdoor",
    list: [
      "Undress completely, lie down, and call the partner 'Dad' or 'Mom'",
      "Expose yourself on the balcony or in the garden for a while, enjoying the touch of nature",
      "Lick the opponent's feet for 30 seconds",
      "[Penalty] Insert an anal plug and keep it until the end of the game",
      "Lick the partner's anus for 15 seconds",
      "Strip naked",
      "Suck and bite the partner's nipples for 20 seconds",
      "[Bonus] The partner drinks your urine",
      "Take a photo of giving oral sex to the partner",
      "Make love while talking on the phone with parents",
      "Hold the opponent's testicles or clitoris in your mouth for 30 seconds",
      "Let your dog go out to buy condoms",
      "Spank the partner's buttocks until they turn red",
      "Make love while talking on the phone with parents",
      "[Penalty] Wear a blindfold throughout until the end of the game",
      "Pour yogurt on the partner's nipple, lick it clean, and eat it",
      "Drink his/her urine",
      "Suck and nibble on the partner's fingers for 10 seconds like oral sex",
      "Insert a lollipop into the male and then lick it repeatedly five times",
      "Record a video of fondling the breasts in front of a mirror for 10 seconds",
      "Fill the vagina with beer/water for the male lead to use",
      "Hold the partner's testicles or clitoris in your mouth for 10 seconds",
      "[Penalty] Send your naked body photo to the author",
      "Let the partner step on your chest or testicles for 10 seconds",
      "French kiss with the partner for half a minute",
      "The partner stands while you kneel and help them [him/her] orally for 10 seconds",
      "Lick the opponent's feet for 30 seconds",
      "Expose yourself on the balcony or in the garden for a while, enjoying the touch of nature",
      "Tie TA up with a rope and whip for 15 seconds",
      "The partner stands while you kneel and help them [him/her] orally for one minute",
      "Make love freely in the hallway",
      "Lie down, lift your buttocks, and let the male lead vary the speed and depth of penetration",
      "Let the male lead forcefully knead and rub the breasts, using two fingers to pinch and twist the nipples",
      "Lie on the ground and imitate a dog's bark",
      "Wear a blindfold and enjoy the partner licking any part for one minute",
    ],
  },
  {
    name: "SM",
    list: [
      "Take off your clothes and lie down on the ground and call the other person's father/mother",
      "Be naked for a while on the balcony or in the garden and enjoy the touch of nature",
      "Lick your opponent's feet for 30 seconds",
      "[Punishment] Use an anal plug until the game is over",
      "Lick each other's asshole for 15 seconds",
      "Take off",
      "Suck and bite each other's nipples for 20 seconds",
      "[Benefit] The other person drinks your urine",
      "Take a picture of giving someone a blowjob",
      "Having sex while calling your parents",
      "Hold your partner's balls or clitoris with your mouth for 30 seconds",
      "Take your puppy vacuum out and buy condoms",
      "Spank the other person's ass until it turns red",
      "Having sex while calling your parents",
      "[Punishment] Wear a blindfold throughout the entire game until the end of the game",
      "Pour yogurt on the other person's nipples, lick them clean and eat them",
      "Drink her/his urine",
      "Suck each other's fingers for 10 seconds like oral sex",
      "A man uses a lollipop to penetrate and then lick it five times.",
      "Make a 10-second video of breast rubbing in front of the mirror",
      "Fill the vagina with beer/white water for the male protagonist to drink",
      "Hold your partner's balls or clitoris with your mouth for 10 seconds",
      "[Punishment] Send your nude body to the author",
      "The opponent stepped on the chest or balls with his feet for 10 seconds",
      "Kiss each other with your tongue for half a minute",
      "The other person stands and you kneel down and give him or her a mouth for 10 seconds.",
      "Lick your opponent's feet for 30 seconds",
      "Be naked for a while on the balcony or in the garden and enjoy the touch of nature",
      "Tie him up with a rope and whip him for 15 seconds",
      "Kneel while the other person stands and give him or her a mouth for one minute.",
      "Let's go have sex in the corridor",
      "The male protagonist lies on his back and sticks his butt out, thrusting at will with varying speeds, slowness and depth",
      "The male protagonist violently rubbed her breasts and pinched her nipples with two fingers",
      "Lie down on the ground and learn how to bark",
      "Wear a blindfold and enjoy the other person licking any part of your body for one minute",
    ],
  },
  {
    name: "Maid",
    list: [
      "Pinching the male protagonist's shoulders and beating his back and constantly sucking on the male protagonist's earlobes",
      "Help the male protagonist take out his penis from the zipper and stimulate it with the tip of his tongue",
      "Put the male protagonist's penis upright and use his private parts to massage his penis 360 degrees around",
      "Kneel down with your hands behind your back and give the male protagonist a selfless blowjob and record a video",
      "Kneel down with your hands behind your back and be fucked crazily by the male protagonist for a minute.",
      "I was forced to lie down on a dog leash and lick the male lead's penis. If I couldn't do it well, I was whipped hard.",
      "After I opened my honey hole, I was wildly fucked by the male protagonist with a cucumber",
      "The male protagonist sucked the clitoris with his mouth for two minutes and kept licking it with his tongue.",
      "Continuously changing positions, the male protagonist took 10 photos of his vagina exposed as mobile phone wallpaper",
      "The male protagonist smeared ketchup on his penis and asked the maid to lick it clean several times.",
      "The male protagonist inserted his underwear and private parts, moaning and twisting his buttocks",
      "Being hugged and kissed by the male protagonist, he squeezed the bear with his left hand and stroked and fucked his honey hole with his right hand",
      "Do a strip dance for the male protagonist and lift up his clothes so that the male protagonist can kiss and knead his breasts",
      "Take a shower together and put shower gel on each other. You are not allowed to wash until the game is over.",
      "After fierce resistance, he was raped by the male protagonist. In order not to suffer a loss, he raped the male protagonist",
      "Oil your hands and change various gestures to give the male protagonist JJ an exquisite SPA",
      "I touched my breasts and pressed the model's pussy, saying I was so lonely and the male host filmed me",
      "The maid swallowed the penis with her vagina, tightened her vagina and cupped it repeatedly for the male protagonist",
      "Being penetrated by the male protagonist in a lustful position for one minute",
      "Kneel down and the male protagonist grabs your arms with both hands and uses your penis to penetrate your anus for a minute.",
      "The male protagonist stuffed popping candy into her lower body and then violently fucked her for 30 seconds",
      "Continuously licking, sucking, and swirling the tongue until the male protagonist climaxes, ejaculates orally, and swallows semen.",
      "The boy lies on the ground, and the girl squats on the boy's face for him to watch for 15 seconds (no touching)",
      "I'll stick my butt open, touch my clit, and beg the male protagonist to fuck me to death.",
      "The nipples were sucked crazily and the male protagonist put his underwear into his underwear and fucked with his fingers",
      "Fill the vagina with beer/white water for the male protagonist to drink",
      "Let the shower room turn on and give the male protagonist a blowjob",
      "Use both breasts to massage the male protagonist's back and buttocks with oil until the male protagonist is satisfied.",
      "I lay on my knees and was violently penetrated and withdrawn by the male protagonist several times until I begged for mercy.",
      "The male protagonist violently rubbed her breasts and pinched her nipples with two fingers,",
    ],
  },
  {
    name: "Butler",
    list: [
      "The heroine smeared ketchup on her private parts and asked the male servant to lick it clean several times.",
      "While being kissed by the queen, she touched the private parts of the male servant through her clothes with her hands",
      "The Queen held up her chin with one hand to admire her, and put her other hand into her pants to play with the valet's JJ and balls.",
      "Sit on the valet and caress his chest, lift the BRA and touch the tip of his nose with your nipples to tease",
      "Write so-and-so on the butt of a valet and ask him to stick out his butt and grab his penis for a photo.",
      "Order the valet to beat his back with his penis for two minutes",
      "Use the glans to massage the queen's breasts for two minutes",
      "Smear yogurt on the chest and let the valet lick it clean",
      "Order the valet to masturbate",
      "Order the valet to dip his penis into ketchup and feed it to the Queen",
      "Lift up your underwear and order the valet to kiss the chest, while twisting your buttocks and rubbing the valet's private parts",
      "The man takes the woman's clitoris and sucks it until the woman yells stop",
      "Listen to the Queen shouting commands (1, 2, 1) sometimes fast and sometimes slowly, and the male servant thrusts according to the rhythm",
      "Try every possible way to make the other person have an erection or bleed water",
      "The Queen inserted a lollipop into her private parts and let the male servant lick it",
      "The valet massages the Queen's back and uses oil on her JJ to massage her vagina",
      "Order the valet to thrust and ejaculate quickly and spread it evenly on the chest to make a semen SPA on the chest.",
      "The queen raised her buttocks and slapped her buttocks with her hands and said to the male servant: If you are a man, fuck me to death",
      "The valet wore a blindfold and massaged the Queen's breasts for two minutes",
      "The queen peeled a banana and masturbated repeatedly and fed it to the male servant to eat",
      "Write the Queen's name on the valet's erect penis and ask the valet whose penis it is.",
      "The male servant crosses his legs to tighten the vaginal opening when thrusting",
      "Let the manservant swirl his tongue around the clitoris for one minute and suck the clitoris with his tongue for one minute.",
      "Order the valet to kiss the neck and breasts and at the same time take out the valet's penis and play with it",
      "She ordered the valet to do an explosive striptease, and after dragging him down to his underwear, the Queen squeezed his balls and penis hard.",
      "Using a pulsating bottle to masturbate the valet, oiling up the penis and stuffing it all into the bottle",
      "Order the valet to ejaculate inside and then have him perform oral sex to lick the semen that drips out",
      "Ride on the back of a male servant and shout 'drive, drive, drive', and use a whip to whip your buttocks to play horse riding games.",
      "Order the male servant to lick and kiss the private parts through his underwear",
      "The king masturbated with his hands and asked the valet to suck his fingers several times.",
      "Order the male servant to rub the clitoris and vagina with the glans for three minutes (no entry)",
      "Let the valet rub the penis three times on the vulva and then insert it once, repeating the cycle 20 times",
    ],
  },
];
