export const configEN = {
  level1: [
    "Meow three times",
    "Take a funny selfie together",
    "Whisper to each other",
    "Press the other person's calf for 1 minute",
    "Maintain eye contact for 5 seconds",
    "Feed each other water",
    "Hold hands for 30 seconds",
    "Hug for 30 seconds",
    "Maintain eye contact for 5 seconds",
    "Attempt to kiss",
    "Share your first impression of each other",
    "Hold hands for one minute",
    "Let the other person close their eyes while you apply lipstick",
    "Give each other a massage",
    "Act out Zhu Bajie carrying his wife",
    "Touch the other person's ear for 2 seconds",
    "Pat the other person's head for 10 seconds",
    "Sing a song to each other",
    "Have a drink together",
    "Attempt to kiss again",
    "Create a confession video for each other as a memory",
    "Comb the other person's hair",
    "Have the other person stand while you kneel and feed them",
    "Give the other person a 1-minute massage on their back",
    "Meow three times",
    "Kiss the back of the other person's hand for 30 seconds",
    "Hug for one minute",
    "Maintain eye contact for 5 seconds",
    "Take another funny selfie",
    "Kiss the other person's hand",
    "[Penalty] Be tickled for 30 seconds",
    "Hug from behind for 1 minute",
    "Kiss the other person's forehead",
  ],
  level2: [
    "Gently blow air near the other person's ear 10 times",
    "Kiss in front of a mirror",
    "Sequentially kiss the other person's face, neck, and collarbone",
    "Lie down and give the other person a 1-minute massage",
    "Press the other person under you and do ten push-ups",
    "Both crawl under the covers and kiss",
    "Maintain eye contact for 20 seconds",
    "Take a shower together on the same day",
    "Raise your buttocks and let the other person spank you 10 times",
    "Gently touch the sensitive area of the other person for 30 seconds",
    "Hug each other for 1 minute and caress each other's buttocks",
    "The guy princess-carries the girl and holds for 15 seconds",
    "Close your eyes and let the other person do whatever they want for 1 minute",
    "Kiss the other person's cheek",
    "French kiss for 30 seconds",
    "Gently rub the other person's buttocks",
    "Take off the specified clothing of the other person",
    "Gently touch the other person's chest for 30 seconds",
    "French kiss with a method for 20 seconds",
    "Take off one piece of clothing",
    "Kneel down and kiss the other person's hand",
    "Gently touch the other person's thighs for 30 seconds",
    "Kiss the other person's chest for 30 seconds",
    "Turn away and wiggle your butt towards the other person",
    "Buy a sexy item",
    "Do nothing",
    "Take off one piece of clothing",
    "Gently lick the other person's earlobe for 10 seconds",
    "Use an ice cube to gently slide over the other person's body until it melts",
    "Give the other person a gentle foot massage for 2 minutes",
    "Perform a sexy dance for 1 minute",
    "Blindfold the other person with a scarf or blindfold and play a sensory exploration game",
    "Watch an erotic movie together or read an erotic novel, then discuss your feelings",
    "Create a sexual guide for both of you, including preferences, desires, and limits",
    "Find a quiet outdoor spot, kiss the other person's entire body, and enjoy the beauty of nature",
    "Use food for kissing and licking, such as chocolate sauce or fresh fruit",
    "Experiment with new sexual positions or techniques together for added excitement",
    "Gently stimulate the other person's ear with your tongue",
    "Gently bite the other person's earlobe",
    "Give the other person a relaxing shoulder massage",
    "Gently caress the other person's lower body for 30 seconds, providing pleasure",
    "Close your eyes and let the other person do anything to you for one minute",
    "Gently knead the other person's buttocks",
    "Remove any piece of clothing as specified by the other person",
    "Gently caress the other person's chest for 30 seconds",
    "Try a new intimate position together",
    "Use your hands to gently touch sensitive areas on each other",
    "Slide an ice cube over the other person's body for 30 seconds",
    "Write a sweet message on the other person's body with lipstick",
    "Put on sexy lingerie and give the other person a private performance",
    "Sing a song or recite a poem for the other person",
    "Imitate the other person's voice and mannerisms, playing a role-playing game",
    "Expose yourself for a moment on the balcony or in the garden, enjoying the natural sensations",
    "Wear a blindfold until the end of the game",
  ],
  level3: [
    "Take off the other person's underwear",
    "Lick the other person's ears for 10 seconds",
    "Give the other person a leg massage",
    "[Bonus] Lie down, and let the other person massage you for one minute",
    "Deeply kiss the other person for 30 seconds",
    "Tickle the other person until they beg for mercy, at least 10 seconds",
    "Take off one piece of clothing from the other person",
    "Take off all of the other person's clothes",
    "Tease sensitive areas of the other person for 15 seconds",
    "Let the other person grab your chest inside your underwear for 10 seconds",
    "The woman is princess-carried by the man and they walk around the room once",
    "Pour alcohol or yogurt on yourself, and let the other person lick it clean",
    "Take a selfie video of you kissing",
    "Drink a toast and take a photo",
    "Strip completely",
    "Suck the other person's fingers with your mouth for 10 seconds",
    "Let the other person lick various parts of your upper body for more than 30 seconds",
    "Lay down, and let the other person lick your back for 20 seconds",
    "Suck the other person's chest for 20 seconds",
    "Wet kiss with the other person for 10 seconds",
    "Kiss the inside of the other person's thighs for 10 seconds",
    "Strip completely",
    "Tie the other person's hands until the punishment is over",
    "Touch the other person's chest or spank their buttocks once",
    "Let the other person's hand touch inside your pants and freely touch for 10 seconds",
    "[Bonus] Let the other person perform oral sex on you for 30 seconds",
    "Massage the other person's breasts for a moment",
    "Lick the other person's neck to chest for 30 seconds",
    "Lick or lightly bite the other person's earlobe five times",
    "Kneel down and lick the other person for 30 seconds",
    "[Bonus] Lie down and enjoy being licked all over your body by the other person for 1 minute",
    "Try to make the other person aroused or wet in any way",
  ],
  level4: [
    "Help the opponent hold the testicles or clitoris for 10 seconds while swirling the tongue",
    "[Penalty] Raise your buttocks and let the other person spank you three times",
    "[Bonus] The other person gives you oral pleasure in a designated area for one minute",
    "Apply oil, chest to chest, and help the opponent push the chest for 30 seconds",
    "Lick the opponent's silk feet or fingers for 10 seconds",
    "Strip naked [or wear sexy lingerie]",
    "Wet kiss with the opponent for 10 seconds",
    "Suck the opponent's fingers for 10 seconds",
    "The woman wears sexy lingerie, and the man licks the opponent's back for 1 minute",
    "Let the opponent bite and rub the nipple with their teeth for 10 seconds",
    "[Bonus] The opponent kisses you with water on your body for 30 seconds",
    "Hold the opponent's testicles or clitoris in your mouth for 10 seconds",
    "Reach from behind and massage the chest for 30 seconds",
    "Rear-entry thrust 20 times without ejaculating",
    "Have mutual breast sex for 30 seconds",
    "Let the opponent bite and rub the nipple with their teeth for 10 seconds",
    "Pour yogurt on the opponent's nipple and lick it clean",
    "Massage the opponent's chest 3 times or lightly bite the opponent's earlobe 5 times",
    "Do everything possible to make the opponent aroused or wet",
    "Rear-entry penetration 20 times and record a video for memories",
    "Record a 15-second video of giving oral pleasure to the opponent",
    "The man stands, lifts the woman, and inserts 20 times without ejaculating",
    "Record a video of fondling the breasts in front of a mirror for 10 seconds",
    "Rub the face of the opponent with your chest or genitals for 10 seconds",
    "Lick the opponent's neck to chest for 30 seconds",
    "Practice Kama Sutra's 'Lotus' position for 30 seconds without ejaculating",
    "[Bonus] The opponent licks various parts of your body for 1 minute",
    "[Bonus] The opponent helps you by licking all parts of your body for 2 minutes",
    "Hold the opponent's testicles or clitoris in your mouth for 30 seconds",
    "Let the opponent use their genitals to slap your face 3 times or rub them on your face for 10 seconds",
    "Use your hand to stimulate yourself for 1 minute or [do something else] 30 times",
    "Hold hot water in your mouth and give oral pleasure to the opponent for 30 seconds",
    "Record a video of lovemaking with the opponent",
    "Hold ice water or ice in your mouth and give oral pleasure to the opponent for 30 seconds",
    "The opponent stands while you kneel and help them [him/her] orally for 1 minute",
    "Rear-entry thrust 20 times without ejaculating",
  ],
  level5: [
    "French kiss with the partner for 10 seconds",
    "Get the partner aroused or wet",
    "Lick the opponent's neck to chest for 30 seconds",
    "[Penalty] The opponent sits on you with their back facing until the end of the game",
    "Give the partner oral sex for 15 seconds",
    "Strip naked",
    "Suck and bite the partner's nipples for 20 seconds",
    "[Bonus] The partner feeds you with their mouth",
    "Take a photo of giving oral sex to the partner",
    "Make love while talking on the phone with parents",
    "Hold the opponent's testicles or clitoris in your mouth for 10 seconds",
    "Rear-entry thrust 20 times without ejaculating",
    "Massage the partner's chest or tweak it",
    "Have mutual breast sex for half a minute",
    "The partner stands while you kneel and help them [him/her] orally for 10 seconds",
    "Pour yogurt on the partner's nipple, lick it clean, and eat it",
    "Let the partner pull out one hair",
    "Suck and nibble on the partner's fingers for 10 seconds like oral sex",
    "Open the door and have oral sex at the doorway for 10 seconds",
    "Record a video of fondling the breasts in front of a mirror for 10 seconds",
    "Rub the partner's face with your breast or genitals for 10 seconds",
    "Hold the partner's testicles or clitoris in your mouth for 10 seconds",
    "Lick the partner's neck to chest for 30 seconds",
    "Let the partner step on your chest or testicles for 10 seconds",
    "French kiss with the partner for half a minute",
    "The partner stands while you kneel and help them [him/her] orally for 10 seconds",
    "Hold the partner's testicles or clitoris in your mouth for half a minute",
    "Suck and bite the partner's nipples for 30 seconds",
    "Rear-entry for one minute in front of the mirror, no ejaculating allowed",
    "The partner stands while you kneel and help them [him/her] orally for one minute",
    "Lick from the forehead down to the toes",
    "The opponent pours water from the base of your thighs, and you drink it all",
    "Specify any part of your body for the partner to lick for 20 seconds",
    "Wear a blindfold and enjoy the partner licking any part for one minute",
  ],
  level6: [
    "Undress completely, lie down, and call the partner 'Dad' or 'Mom'",
    "Expose yourself on the balcony or in the garden for a while, enjoying the touch of nature",
    "Lick the opponent's feet for 30 seconds",
    "[Penalty] Insert an anal plug and keep it until the end of the game",
    "Lick the partner's anus for 15 seconds",
    "Strip naked",
    "Suck and bite the partner's nipples for 20 seconds",
    "[Bonus] The partner drinks your urine",
    "Take a photo of giving oral sex to the partner",
    "Make love while talking on the phone with parents",
    "Hold the opponent's testicles or clitoris in your mouth for 30 seconds",
    "Let your dog go out to buy condoms",
    "Spank the partner's buttocks until they turn red",
    "Make love while talking on the phone with parents",
    "[Penalty] Wear a blindfold throughout until the end of the game",
    "Pour yogurt on the partner's nipple, lick it clean, and eat it",
    "Drink his/her urine",
    "Suck and nibble on the partner's fingers for 10 seconds like oral sex",
    "Insert a lollipop into the male and then lick it repeatedly five times",
    "Record a video of fondling the breasts in front of a mirror for 10 seconds",
    "Fill the vagina with beer/water for the male lead to use",
    "Hold the partner's testicles or clitoris in your mouth for 10 seconds",
    "[Penalty] Send your naked body photo to the author",
    "Let the partner step on your chest or testicles for 10 seconds",
    "French kiss with the partner for half a minute",
    "The partner stands while you kneel and help them [him/her] orally for 10 seconds",
    "Lick the opponent's feet for 30 seconds",
    "Expose yourself on the balcony or in the garden for a while, enjoying the touch of nature",
    "Tie TA up with a rope and whip for 15 seconds",
    "The partner stands while you kneel and help them [him/her] orally for one minute",
    "Make love freely in the hallway",
    "Lie down, lift your buttocks, and let the male lead vary the speed and depth of penetration",
    "Let the male lead forcefully knead and rub the breasts, using two fingers to pinch and twist the nipples",
    "Lie on the ground and imitate a dog's bark",
    "Wear a blindfold and enjoy the partner licking any part for one minute",
  ],
  level7: [
    "去楼道里尽情做爱吧",
    "在阳台或花园里裸露一会儿，享受自然的触感",
    "边打电话给父母边做爱",
    "让你的小狗真空出去买避孕套",
    "去楼下拍个户外写真照吧",
    "【惩罚】所有户外活动全程佩戴跳蛋直到游戏结束",
    "让他/她牵着您去外面遛一遛",
    "去楼道里尽情做爱吧",
    "脱光衣服趴在地方叫对方爸爸/妈妈",
    "去楼道里尽情做爱吧",
    "边打电话给父母边做爱",
    "像口交一样吸吮对方手指",
    "车震要不要体验一下",
    "去电梯里面露出",
    "去超市买东西并露出",
    "去楼道里尽情做爱吧",
    "福利】对方在外面叫你爸爸/妈妈",
    "【惩罚】把您的裸体发给作者",
    "拍一张给对方口交的照片",
    "对着阳台后入一分钟，不许射",
    "真空逛超市",
    "让女方穿上黑丝与高跟去加一个异性微信",
    "屁股上写上您是肉便器",
    "对方站着自己跪着帮他（她）口一分钟",
    "去楼道里尽情做爱吧",
    "脱光衣服趴在地方叫对方爸爸/妈妈",
    "舔对手的脚30秒",
    "【惩罚】把您的裸体发给作者",
    "将酸奶倒在对方乳头上舔干净吃掉",
    "让你的小狗真空出去买避孕套",
    "让男方给他的异性朋友表白",
    "让他/她牵着您去外面遛一遛",
  ],
  level8: [
    "为男主捏肩捶背并不断吸吮男主耳垂",
    "帮男主从拉链处掏出JJ用舌尖刺激",
    "竖起男主JJ用私处为JJ做360度环绕按摩",
    "跪着双手拷背后为男主忘我的kou交并拍视频",
    "跪着双手拷背后被男主疯狂的抽插嘴巴一分钟",
    "被牵狗绳趴着为男主舔JJ舔不好就被狠抽皮鞭",
    "自己扒开蜜穴后被男主用黄瓜疯狂抽插",
    "阴蒂被男主用嘴巴嘬住不放两分钟并不停舌舔",
    "不断变化姿势让男主拍10张露yin道做手机壁纸",
    "男主JJ上涂番茄酱让女仆舔食干净反复数次",
    "被男主伸进内裤和私处，边呻吟边扭动屁股",
    "被男主后抱亲吻，左手捏熊右手抚摸抽插蜜穴",
    "为男主跳脱衣热舞掀衣让男主亲吻揉捏乳房",
    "一起洗澡，并给对方打上沐浴露，游戏结束前不准洗",
    "激烈反抗后被男主强奸，为了不吃亏把男主强奸",
    "双手涂油变换各种手势为男主JJ做精致SPA",
    "自摸胸部并扣模蜜穴说我好寂寞被男主拍视频",
    "女仆用阴道吞下JJ收紧阴道为男主反复拔罐",
    "被男主用色戒的姿势抽插一分钟",
    "趴跪被男主双手抓胳膊用JJ爆菊花一分钟",
    "被男主再下体塞跳跳糖后猛烈抽插30秒",
    "不断舌舔吸撸舌头打转让男主高潮口射并吞精",
    "男生躺在地上，女生蹲在男脸上让男观看15秒（禁止触摸）",
    "撅腚剥开蜜穴自摸阴蒂求男主CAO死自己算了",
    "被疯狂吸吮乳头并被男主伸进内裤用手指抽插",
    "在阴道中倒满啤酒/白水供男主引用",
    "再淋浴房开着淋浴帮男主kou交",
    "用双乳为男主推油按摩背部和臀部至男主满意",
    "趴跪着被男主不断猛烈插入抽出数次至求饶为止",
    "被男主暴力揉搓乳房并用两指夹住乳头使劲揪",
  ],
  level9: [
    "女主私处上涂番茄酱让男仆舔食干净反复数次",
    "被女王一边亲吻，一边用手隔着衣服抚摸男仆私处",
    "被女王一只手托起下巴欣赏，另一只手伸进裤子把玩男仆JJ和蛋蛋",
    "坐男仆身上抚摸胸部并掀起BRA用乳头碰他鼻尖挑逗",
    "在男仆屁股上写某某的男仆让其撅屁股抓住JJ拍照留念",
    "命男仆用JJ捶背两分钟",
    "用gui头为女王胸部按摩两分钟",
    "胸部涂抹酸奶让男仆舔干净",
    "命令男仆自慰打飞机",
    "命令男仆用JJ蘸番茄酱喂女王吃",
    "掀起内衣命令男仆亲吻胸部，同时扭动屁股摩擦男仆私处",
    "男含女阴蒂吸吮直到女生喊停",
    "听女王喊口令（1、2、1）时快时慢男仆按节奏抽插",
    "想尽办法弄对方勃起或流水",
    "女王把棒棒糖塞入私处让男仆舌舔",
    "男仆为女王做背部推油并JJ涂油为阴道推油",
    "命男仆快速抽插拨出射在胸部涂抹均匀为胸部做jing液SPA",
    "女王撅起屁股手拍屁股对男仆说：是男人就把我CAO死",
    "男仆带眼罩为女王丰胸按摩两分钟",
    "女王剥跟香蕉反复自慰后喂男仆吃掉",
    "在男仆勃起的JJ上写上女王名字问男仆这是谁的",
    "男仆抽插时双腿交叉着收紧阴道口",
    "让男仆舌头围阴蒂打转一分钟吸住阴蒂舌舔一分钟",
    "命男仆亲吻脖颈部和酥胸同时掏出男仆JJ把玩",
    "命男仆跳劲爆脱衣舞，拖到只剩内裤后被女王使劲捏蛋蛋和JJ",
    "用脉动瓶子给男仆自慰，JJ涂油全部塞入瓶内",
    "命男仆内射再让其口交把淌出来的jing液舔干净",
    "骑男仆背上喊驾驾驾，用皮鞭抽腚演骑马游戏",
    "命男仆隔着内裤舌舔亲吻私处",
    "王用手自慰后让男仆吸吮手指反复多次",
    "命男仆用龟头不停摩擦阴蒂和阴道三分钟（禁止进入）",
    "让男仆JJ在外阴摩擦三次然后内插一次，循环往复20次",
  ],
};
